# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B package --file pom.xml

  Deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: fetch code
     uses: actions/checkout@v2
    - name: Set up JDK 1.8
     uses: actions/setup-java@v1
     with:
       java-version: 1.8
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: deploy
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: root
        key: ${{ secrets.CITY_MAPPER }}
        source: "target/demo-1.0-SNAPSHOT.jar"
        target: "deployment"
    - name: ls -a via ssh
      uses: fifsky/ssh-action@master
      with:
       command: |
        cd ~/deployment/target
        nohub java -jar demo-1.0-SNAPSHOT-jar-with-dependencies.jar &
       host: ${{ secrets.HOST }}
       user: root
       key: ${{ secrets.CITY_MAPPER}}